
    function getSupportedFonts() {
        return [
            {
                name: 'Serif',
                value: 'Times',
                aliases: ['Times']
            },
            'Sans-Serif',
            'Monospace',
            'Neuton', {
                name: 'Cursive',
                value: 'Comic Neue',
                aliases: ['Cursive1', 'Cursive']
            }, {
                name: 'Arial',
                value: 'Arial',
                aliases: ['ArialMT', 'Arial-BoldMT']
            }, {
                name: 'Museo Slab',
                value: 'Museo Slab',
                aliases: ['MuseoSlab']
            }, {
                name: 'Museo Sans',
                value: 'Museo Sans',
                aliases: ['MuseoSans']
            }, {
                name: 'Stag Medium',
                value: 'Stag Medium',
                aliases: ['Stag-Medium', 'Eurostile LT Bold']
            }, {
                name: 'Stag Sans Medium',
                value: 'Stag Sans Medium',
                aliases: ['STAGSANS']
            }, {
                name: 'Zapf ChanceC',
                value: 'Zapf ChanceC',
                aliases: ['Zapf']
            }, {
                name: 'Gill Sans MT Ext Condensed Bold',
                value: 'Gill Sans MT Ext Condensed Bold',
                aliases: ['GLSNECB']
            }, {
                name: 'Helvetica',
                value: 'HelveticaCnd-Normal',
                aliases: ['HELVETIA']
            }, {
                name: 'CG-OmegaC',
                value: 'CG-OmegaC',
                aliases: ['CG Omega']
            }, {
                name: 'Space-text',
                value: 'Space-text',
                alias: ['Space-text']
            }, {
                name: 'Viga',
                value: 'Viga',
                alias: ['Viga']
            }, {
                name: 'Decalotype',
                value: 'Decalotype',
                alias: ['Decalotype']
            }, {
                name: 'Titillium',
                value: 'Titillium',
                alias: ['Titillium']
            }, {
                name: 'Inknut-antiqua',
                value: 'Inknut-antiqua',
                alias: ['Inknut-antiqua']
            }, {
                name: 'Neuton',
                value: 'Neuton',
                alias: ['Neuton']
            }, {
                name: 'Aladin',
                value: 'Aladin',
                alias: ['Aladin']
            }, {
                name: 'Aleo',
                value: 'Aleo',
                alias: ['Aleo']
            }, {
                name: 'Amita',
                value: 'Amita',
                alias: ['Amita']
            }, {
                name: 'Archivo',
                value: 'Archivo',
                alias: ['Archivo']
            }, {
                name: 'ArimaKoshi',
                value: 'ArimaKoshi',
                alias: ['ArimaKoshi']
            }, {
                name: 'Asul',
                value: 'Asul',
                alias: ['Asul']
            }, {
                name: 'Baloo',
                value: 'Baloo',
                alias: ['Baloo']
            }, {
                name: 'Blackout',
                value: 'Blackout',
                alias: ['Blackout']
            }, {
                name: 'Cabin',
                value: 'Cabin',
                alias: ['Cabin']
            }, {
                name: 'Changa',
                value: 'Changa',
                alias: ['Changa']
            }, {
                name: 'Condiment',
                value: 'Condiment',
                alias: ['Condiment']
            }, {
                name: 'Corben',
                value: 'Corben',
                alias: ['Corben']
            }, {
                name: 'Cormorant',
                value: 'Cormorant',
                alias: ['Cormorant']
            }, {
                name: 'CroissantOne',
                value: 'CroissantOne',
                alias: ['CroissantOne']
            }, {
                name: 'DeliusSwashCaps',
                value: 'DeliusSwashCaps',
                alias: ['DeliusSwashCaps']
            }, {
                name: 'Devonshire',
                value: 'Devonshire',
                alias: ['Devonshire']
            }, {
                name: 'Digitalt',
                value: 'Digitalt',
                alias: ['Digitalt']
            }, {
                name: 'DrSugiyama',
                value: 'DrSugiyama',
                alias: ['DrSugiyama']
            }, {
                name: 'Elsie',
                value: 'Elsie',
                alias: ['Elsie']
            }, {
                name: 'ElsieSwashCaps',
                value: 'ElsieSwashCaps',
                alias: ['ElsieSwashCaps']
            }, {
                name: 'Fanwood Text',
                value: 'Fanwood Text',
                alias: ['Fanwood Text']
            }, {
                name: 'Fondamento',
                value: 'Fondamento',
                alias: ['Fondamento']
            }, {
                name: 'Fascinate',
                value: 'Fascinate',
                alias: ['Fascinate']
            }, {
                name: 'FredokaOne',
                value: 'FredokaOne',
                alias: ['FredokaOne']
            }, {
                name: 'Gabriela',
                value: 'Gabriela',
                alias: ['Gabriela']
            }, {
                name: 'Galada',
                value: 'Galada',
                alias: ['Galada']
            }, {
                name: 'GermaniaOne',
                value: 'GermaniaOne',
                alias: ['GermaniaOne']
            }, {
                name: 'GlacialIndifference',
                value: 'GlacialIndifference',
                alias: ['GlacialIndifference']
            }, {
                name: 'Gnomon-Foreground',
                value: 'Gnomon-Foreground',
                alias: ['Gnomon-Foreground']
            }, {
                name: 'Heuristica',
                value: 'Heuristica',
                alias: ['Heuristica']
            }, {
                name: 'HKGrotesk',
                value: 'HKGrotesk',
                alias: ['HKGrotesk']
            }, {
                name: 'HKVenetian',
                value: 'HKVenetian',
                alias: ['HKVenetian']
            }, {
                name: 'IAWriterDuospace',
                value: 'IAWriterDuospace',
                alias: ['IAWriterDuospace']
            }, {
                name: 'IBMPlexMono',
                value: 'IBMPlexMono',
                alias: ['IBMPlexMono']
            }, {
                name: 'IBMPlexSans',
                value: 'IBMPlexSans',
                alias: ['IBMPlexSans']
            }, {
                name: 'IBMPlexSerif',
                value: 'IBMPlexSerif',
                alias: ['IBMPlexSerif']
            }, {
                name: 'Istok',
                value: 'Istok',
                alias: ['Istok']
            }, {
                name: 'Jellee',
                value: 'Jellee',
                alias: ['Jellee']
            }, {
                name: 'Judson',
                value: 'Judson',
                alias: ['Judson']
            }, {
                name: 'Kameron',
                value: 'Kameron',
                alias: ['Kameron']
            }, {
                name: 'Karla',
                value: 'Karla',
                alias: ['Karla']
            }, {
                name: 'Kavivanar',
                value: 'Kavivanar',
                alias: ['Kavivanar']
            }, {
                name: 'KaushanScript',
                value: 'KaushanScript',
                alias: ['KaushanScript']
            }, {
                name: 'LeagueMono',
                value: 'LeagueMono',
                alias: ['LeagueMono']
            }, {
                name: 'Lekton',
                value: 'Lekton',
                alias: ['Lekton']
            }, {
                name: 'LinguisticsPro',
                value: 'LinguisticsPro',
                alias: ['LinguisticsPro']
            }, {
                name: 'MarkoOne',
                value: 'MarkoOne',
                alias: ['MarkoOne']
            }, {
                name: 'Michroma',
                value: 'Michroma',
                alias: ['Michroma']
            }, {
                name: 'Montserrat',
                value: 'Montserrat',
                alias: ['Montserrat']
            }, {
                name: 'NanumGothicCoding',
                value: 'NanumGothicCoding',
                alias: ['NanumGothicCoding']
            }, {
                name: 'Nautilus',
                value: 'Nautilus',
                alias: ['Nautilus']
            }, {
                name: 'Nevis',
                value: 'Nevis',
                alias: ['Nevis']
            }, {
                name: 'Norwester',
                value: 'Norwester',
                alias: ['Norwester']
            }, {
                name: 'Now',
                value: 'Now',
                alias: ['Now']
            }, {
                name: 'Officecodeprod',
                value: 'Officecodeprod',
                alias: ['Officecodeprod']
            }, {
                name: 'OldStandard',
                value: 'OldStandard',
                alias: ['OldStandard']
            }, {
                name: 'OstrichSans',
                value: 'OstrichSans',
                alias: ['OstrichSans']
            }, {
                name: 'Philosopher',
                value: 'Philosopher',
                alias: ['Philosopher']
            }, {
                name: 'Prociono',
                value: 'Prociono',
                alias: ['Prociono']
            }, {
                name: 'Questrial',
                value: 'Questrial',
                alias: ['Questrial']
            }, {
                name: 'Rajdhani',
                value: 'Rajdhani',
                alias: ['Rajdhani']
            }, {
                name: 'Renner',
                value: 'Renner',
                alias: ['Renner']
            }, {
                name: 'Rubik',
                value: 'Rubik',
                alias: ['Rubik']
            }, {
                name: 'Sansation',
                value: 'Sansation',
                alias: ['Sansation']
            }, {
                name: 'SedgwickAve',
                value: 'SedgwickAve',
                alias: ['SedgwickAve']
            }, {
                name: 'Sen',
                value: 'Sen',
                alias: ['Sen']
            }, {
                name: 'SixCaps',
                value: 'SixCaps',
                alias: ['SixCaps']
            }, {
                name: 'SquadaOne',
                value: 'SquadaOne',
                alias: ['SquadaOne']
            }, {
                name: 'TenorSans',
                value: 'TenorSans',
                alias: ['TenorSans']
            }, {
                name: 'TruenoBd',
                value: 'TruenoBd',
                alias: ['TruenoBd']
            }, {
                name: 'WorkSans',
                value: 'WorkSans',
                alias: ['WorkSans']
            }, {
                name: 'Yesteryear',
                value: 'Yesteryear',
                alias: ['Yesteryear']
            }, {
                name: 'Sriracha',
                value: 'Sriracha',
                alias: ['Sriracha']
            },
            'Adventure',
            'ChopinScript',
            'Giddyup Std', {
                name: 'Orial_',
                value: 'Orial_',
                aliases: ['Orial']
            },
            'Rosewood Std Regular',
            'Stencil Std',
            'Scriptina Pro'
        ];
    }
